SELECT 
	OS.CD_OPERADOR_SISTEMA					'ID_USUARIO',	--ID_USUARIO,int(4)
	OS.NM_MATRICULA						'MATRICULA',			--MATRICULA,varchar(40)
	OS.NM_SENHA							'SENHA',				--SENHA,varchar(50)
	OS.NM_OPERADOR						'NOME',			--NOME,varhcar(50)
	OS.NM_EMAIL_OPERADOR				'EMAIL',		--EMAIL,varchar(255)
	OS.NU_CPF						    'DOCUMENTO',					--DOCUMENTO,CHAR(11)
	0									'BL_REGRA_VALIDACAO',
	0									'BL_USUARIO_',
	1									'ID_USUARIO_MANIPULADOR',
	NULL								'IP_ACESO',
	NULL								'DH_ULTIMO_LOGIN',
	NULL								'DH_ULTIMO_ATIVIDADE',
	4635								'VERSAO',
    OS.DH_ATUALIZACAO					'DH_ATUALIZACAO',
	NULL								'DH_ATUALIZACAO_SENHA',
	NULL								'DH_EXPIRACAO_SENHA',
	OS.CD_EXPORTADO						'BL_EXPORTADO',	--BL_EXPORTADO,int(4)
	NULL								'DH_EXPORTADO',
	0									'BL_EXPORTADO_SENHA',
	NULL								'DH_EXPORTADO_SENHA',
	CASE
		WHEN CD_STATUS = 'I' THEN  0
		ELSE 1 END						'CD_STATUS',			--CD_STATUS,char(1)
	GETDATE()							'DH_TIMESTAMP',					--DH_ATUALIZACAO,DATETIME
	0									'QUANTIDADE_TENTATIVA_LOGIN'
FROM
	OPERADOR_SISTEMA OS