
	SELECT distinct
	cd_isento ID_ISENTO
	,null ID_TIPO_ISENTO
	,i.PLACA
	,t.NUMERO_SERIE TAG
	,ID_OSA
	,mv.NM_MARCA_VEICULO MARCA
	,MODELO
	,COR
	,t.ID_CATEGORIA
	,DH_INICIO_VIGENCIA
	,DH_FIM_VIGENCIA
	,null ID_PERIODO
	,null QUANTIDADE_PASSAGEM
	,null QUANTIDADE_PASSAGEM_DISPONIVEL
	,null JSON_DETALHE
	,i.OBSERVACAO
	,null RENAVAM
	,null DOCUMENTO
	,null ANEXO
	,null VERSAO
	,null DH_ATUALIZACAO
	,0 BL_EXPORTADO
	,null DH_EXPORTADO
	,null BL_EXPORTADO_QUANTIDADE_PASSAGEM
	,null DH_EXPORTADO_QUANTIDADE_PASSAGEM
	,CD_STATUS
	,DH_TIMESTAMP
	,null ID_USUARIO_MANIPULADOR
	,null ID_ORIGEM_ISENTO 
	FROM 
		ISENTO i
		left join tag_isento ti on ti.DS_PLACA = i.PLACA --collate Latin1_General_CI_AS
		left join CP_MARCA_VEICULO mv on mv.CD_MARCA_VEICULO = i.CD_MARCA_VEICULO
		left join toll_n1..TAG t on t.PLACA = i.PLACA collate Latin1_General_CI_AS
