SELECT 
CD_PISTA ID_PISTA
,NM_PISTA NOME
,PRA.CD_PRACA ID_LOCAL
,CASE 
	WHEN CD_SENTIDO = 10 THEN 1 -- Norte
	WHEN CD_SENTIDO = 11 THEN 2 -- sull
	WHEN CD_SENTIDO = 1 THEN 3 -- lest
	WHEN CD_SENTIDO = 2 THEN 4 -- oeste
ELSE	
	0
END ID_SENTIDO
,TRY_CAST(NM_PISTA AS INT) ID_PISTA_OSA
,CASE 
	WHEN CD_TPO_PISTA = 2 THEN 1 -- AVI
	WHEN CD_TPO_PISTA = 3 THEN 2 -- MANUAL
	WHEN CD_TPO_PISTA = 4 THEN 4 -- MANUAL
	WHEN CD_TPO_PISTA = 7 THEN 6 -- FREEFLOW
ELSE	
	0
END ID_TIPO_PISTA
,CASE 
	WHEN CD_TPO_PISTA = 2 THEN 3 -- AVI
	WHEN CD_TPO_PISTA = 3 THEN 1 -- MANUAL
	WHEN CD_TPO_PISTA = 4 THEN 1 -- MANUAL
	WHEN CD_TPO_PISTA = 7 THEN 3 -- FREEFLOW
ELSE	
	0
END ID_TIPO_OPERACAO
,IP_PISTA
,NULL ROUTING_KEY
,NULL ID_SISTEMA_SGA
,0 BL_EXPORTADO
,NULL DH_EXPORTADO
,1 CD_STATUS
,GETDATE()DH_TIMESTAMP 

FROM 
	PISTA PIS
	INNER JOIN PRACA PRA ON PRA.CD_PRACA = PIS.CD_PRACA
