SELECT 
	PRA.CD_PRACA ID_LOCAL
	,NM_PRACA NOME
	,CD_PRACA_CONCESSAO NOME_BREVE
	,CD_CONCESSAO ID_CONCESSAO
	,PIS.CD_PISTA_PRACA ID_LOCAL_OSA
	,NULL ID_LOCAL_DBTRANS
	,PRA.ID_TIPO_PRACA ID_TIPO_LOCAL
	,NULL NU_CNPJ
	,NULL NU_TELEFONE
	,IP_PRACA IP_LOCAL
	,IP_FOTOS IP_FOTO
	,NULL IP_MENSAGERIA
	,NULL ROUTING_KEY
	,NULL LATITUDE
	,NULL LONGITUDE
	,NULL ENDERECO_LOCAL
	,1 CD_STATUS
	,GETDATE() DH_TIMESTAMP 
FROM 
	PRACA PRA
	CROSS APPLY(
		SELECT 
			TOP 1
			CD_PRACA,
			CD_PISTA_PRACA
		FROM 
			PISTA PIS
		WHERE
			PIS.CD_PRACA = PRA.CD_PRACA
	) PIS