-- Referente a tabela do Resiliencia MCG_CONCESSAO

select DISTINCT 
    c.CD_CONCESSAO ID_CONCESSAO
    ,c.NM_CONCESSAO NOME
    ,CC.CONCESSAO_ID_ARTESP ID_CONCESSAO_OSA
    ,'' ID_CONCESSAO_DBTRANS -- não achei nenhum campo 
    ,CC.CODIGO_SAP ID_CONCESSAO_SAP
    ,NULL IP_MENSAGERIA
    ,'' RAZAO_SOCIAL -- não sei ao certo qual campo entra aqui
    ,c.NU_CNPJ_CONCESSAO NU_CNPJ
    ,c.NM_LOGRADOURO
    ,c.TL_TELEFONE NU_TELEFONE
    ,c.BL_PORTAL_PAGAMENTO_ONLINE
    ,c.CD_STATUS
    ,getdate() DH_TIMESTAMP
from 
    CONCESSAO c 
INNER join CONCESSAO_COMPLEMENTO CC on
    CC.CD_CONCESSAO = c.CD_CONCESSAO 
INNER join PRACA p on
    p.CD_CONCESSAO = C.CD_CONCESSAO