-- Referente a tabela do Resiliencia MCG_DESCONTO_VIGENCIA
select 
    ID_DESCONTO_VIGENCIA
    ,DATA_HORA_INICIO DH_INICIO
    ,DATA_HORA_FIM DH_FIM
    ,CD_CONCESSAO ID_CONCESSAO
    ,TETO_APLICABILIDADE
    ,CD_OPERADOR_SISTEMA ID_USUARIO_MANIPULADOR
    ,DH_ATUALIZACAO
    ,getdate() DH_TIMESTAMP
from 
    CONFIGURACAO_DESCONTO_VIGENCIA
