--REFERENTE A TABELA MTP_DESCONTO
SELECT
    ID_DESCONTO
    ,ID_DESCONTO_VIGENCIA
    ,ID_SENTIDO
    ,CD_PRACA ID_LOCAL
    ,ID_CATEGORIA
    ,ID_TIPO_PAGTO ID_TIPO_PAGAMENTO
    ,CD_TIPO_DESCONTO ID_TIPO_DESCONTO
    ,CD_TIPO_ORIGEM_DESCONTO ID_TIPO_ORIGEM_DESCONTO
    ,VALOR
    ,VALOR_DUF
    ,'' JSON_INDICADOR 
    ,TEXTO_RECIBO
    ,CD_OPERADOR_SISTEMA ID_OPERADOR_SISTEMA
    ,DH_ATUALIZACAO
    ,GETDATE() DH_TIMESTAMP
FROM 
    CONFIGURACAO_DESCONTO