--Referente a tabela MTP_ISENTO_LOCAL
SELECT 
    CD_ISENTO_PRACA ID_ISENTO_LOCAL
    ,CD_ISENTO ID_ISENTO
    ,P.CD_PRACA ID_LOCAL
    ,GETDATE() DH_TIMESTAMP
 FROM 
    ISENTO_PRACA IPRA
 INNER JOIN PRACA P ON P.CD_PRACA = IPRA.CD_PRACA